pgfSweave-example.pdf:
	../../exec/pgfSweave pgfSweave-example.Rnw
clean:
	rm -rf cache Rplots.* pgfSweave-example.{sh,map,aux,log,pdf,tex} pgfSweave-example-*
cleanforbuild:
	rm -rf cache Rplots.* pgfSweave-example.{sh,map,aux,log,pdf} pgfSweave-example-*
