% 
\documentclass{article}
\usepackage[OT1]{fontenc}
\usepackage[margin=1in]{geometry}
\usepackage{Sweave}
\usepackage{tikz}
\usepackage{verbatim}
\SweaveOpts{keep.source=TRUE, highlight=T}  %with line 8 commented out, 
% there is no problem...Uncomment line 8 and...it will not work with lines 66-68...reusing a code chunk.

\begin{document}

\title{ExamplePGFsweaveProblems}
\author{Alan T. Arnholt}

\maketitle

<<echo=FALSE>>=
library(PASWR)
options(width=60,keep.space=FALSE)
@

To start, I want to be able to write comments to the right of my code which reguires 
\texttt{keep.source=TRUE} inside the \texttt{SweaveOpts()}.  This also means that I will have 
to space my code as it will not be fixed when it is Sweaved.  If I want messy spacing to 
be fixed, it is still possible to use \texttt{tidy=TRUE}, but comments to the right of code 
will not show up in the final document. 



<<fig=T,tikz=T, width=3.5, height=3.5, tidy=F>>=
# This is another histogram with options highlight=FALSE and tidy=FALSE
junk <- morejunk <- more <- rnorm(10000)  # Histogram!
hist(junk, col="yellow", main="Yellow Junk")  # Histogram!
@


The following is one long line of code separated with semicolons.  The comment above
the code will still print.  However, any comments to the right of the code will not print.
<<fig=F, echo=TRUE, tidy=TRUE,highlight=FALSE>>=
  # Small function with highlight=FALSE and tidy=TRUE and some additional garbage.......
  # garbage to see how it wraps.
cip <- function(x=10, n=100, conf.level=0.95){phat <- x/n; z <- qnorm(1-(1 - conf.level)/2); SE <- sqrt(phat*(1-phat)/n); ME <- z*SE; c(phat-ME, phat+ME)}  # cip function
@
Note:  with \texttt{tidy=FALSE} the comment to the right prints!
<<fig=F, echo=TRUE, tidy=FALSE>>=
# Results of cip() with highlight=FALSE and tidy=FALSE and some additional garbage 
# to see how it wraps
cip(x = 356, n = 1200, conf.level = 0.98) # 98% CI for p
@

Just computing some statistics and not printing the graph.
<<eda, fig=FALSE, echo=TRUE, tidy=T, highlight=T>>=
# Results and graph from EDA()
EDA(rnorm(1000))  # EDA applied to random data
@
Printing a graph but no the one that corresponds with the code chunk \texttt{eda}.
<<edaFIG, echo=FALSE, fig=TRUE, results=hide, external=T>>=
EDA(rnorm(1000))
@

Now here is where the problem comes in \ldots I want to show the graph from \texttt{eda}.
Why will lines 66-68 not work with the \texttt{SweaveOpts()} from line 8? If line 8 is commented out,
and lines 66-68 uncommented there is no problem.

<<edaRfig, echo=FALSE, fig=TRUE, results=hide, external=T>>=
<<eda>>
@

The errors when running with \texttt{SweaveOpts()} with uncommented lines 66-68 are below:
\begin{verbatim}
> pgfSweave(file = "C:\\Alans\\Rscripts\\ExamplePGFsweave.Rnw")
Writing to file ExamplePGFsweave.tex
Processing code chunks ...
Called from: driver$writedoc(drobj, chunk)
Browse[1]> 
 1 : keep.source term verbatim
 2 : echo keep.source term verbatim tikz
 3 : echo tidy keep.source term verbatim
 4 : echo keep.source term verbatim
 5 : echo keep.source term verbatim (label=eda)
 6 : keep.source term hide tikz (label=edaFIG)
[1] "rnorm(1000)"
 7 : keep.source term hide tikz (label=edaRfig)
Error in file(srcfile$filename, open = "rt", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(srcfile$filename, open = "rt", encoding = encoding) :
  cannot open file 'C:/Alans/Rscripts/ExamplePGFsweave.Rnw#from line#63#': No such file or directory
\end{verbatim}

Also, the lines (although not an error) 

\begin{verbatim}
Called from: driver$writedoc(drobj, chunk)
Browse[1]> 
\end{verbatim}

only appear when using  \texttt{SweaveOpts()}.  If I were to specify each Sweave option on a separate line
in the preamble instead of on a single line,
then I have to click submit three times ... or in other words, 

\begin{verbatim}
Called from: driver$writedoc(drobj, chunk)
Browse[1]> 
\end{verbatim}

pops up and stops my work flow three times.

\end{document}
